PUT http://localhost:3001/api/obras/64cfca7c552b137b7016ab48
Content-Type: application/json

{
  "title": "Madre",
  "url": "https://www.entescultor.com/fotos/fragmentos/zoom/madre_zoom.jpg",
  "material": "Acero batido y soldado",
  "largo": 45,
  "ancho": 34,
  "alto": 80,
  "serie": "Fragmentos"
}